name: Node.js Bot CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: |
          if [ -f tsconfig.json ]; then
            npm run build || echo "No build script"
          fi

      - name: Start bot (only if main file exists)
        run: |
          if [ -f index.js ]; then
            node index.js
          elif [ -f main.js ]; then
            node main.js
          else
            echo "No start file found"
          fi
```
